### ISSUE TITLE
Add new cert-manager spec.acme.preferredChain required value

### ISSUE THREAD

**Issue by ElArtista** [ebrianne/helm-charts#2]
Relevant error:

```
STDERR:
  Error: UPGRADE FAILED: failed to create resource: ClusterIssuer.cert-manager.io "cert-manager-webhook-duckdns-staging" is invalid: spec.acme.preferredChain: Invalid value: "null": spec.acme.preferredChain in body must be of type string: "null"
```

**Comment by ElArtista** [comment]
Note: Modifying cluster issuer (e.g. https://github.com/ebrianne/helm-charts/blob/fd6ce72a895f469a6b19a017c8a536f1c98a6da7/charts/cert-manager-webhook-duckdns/templates/production.cluster-issuer.yaml#L11) yaml files like this
```
...
spec:
  acme:
    email: {{ .Values.clusterIssuer.email }}
    privateKeySecretRef:
      name: {{ include "cert-manager-webhook-duckdns.fullname" . }}-production
    server: https://acme-v02.api.letsencrypt.org/directory
    preferredChain: "ISRG Root X1"
...
```

Makes it work.

**Comment by ebrianne** [comment]
Could you provide a bit more informations? 
- Cluster type?
- Kubernetes distribution and version?
- Commands used to deploy the chart?

**Comment by ElArtista** [comment]
I'm using `k3s` version: `v1.20.4-k3s1` (from kubectl nodes -o wide)

Relevant helmfile:
```
repositories:
  # Jetstack charts, https://github.com/jetstack/cert-manager/blob/master/deploy/charts/
  - name: jetstack
    url: https://charts.jetstack.io
  # Ebrianne charts, https://ebrianne.github.io/helm-charts
  - name: ebrianne.github.io
    url: https://ebrianne.github.io/helm-charts

releases:
  # Certificate management controller
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: ingress
    version: v1.2.0
    set:
      - name: installCRDs
        value: true

  # ACME webhook for DuckDNS
  - name: cert-manager-webhook-duckdns
    #chart: ebrianne.github.io/cert-manager-webhook-duckdns
    chart: ebrianne.github.io/cert-manager-webhook-duckdns
    namespace: ingress
    values:
      - values/cert-manager-duckdns.yaml.gotmpl
    needs:
      - ingress/cert-manager
```

**Comment by ElArtista** [comment]
I think its a recent cert-manager change, described here: https://cert-manager.io/docs/configuration/acme/#use-an-alternative-certificate-chain

**Comment by ebrianne** [comment]
Ok this is something that I need to check. I did not run into that problem for my k3s cluster. It should be relatively easy to fix.

**Comment by ebrianne** [comment]
It must be something specific to your installation of cert-manager. I am trying to reproduce the error by deploying a local kind cluster, but I cannot reproduce it... Here are the steps:
```
kind create cluster --name kind

kc get nodes -o wide
NAME                 STATUS   ROLES                  AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE       KERNEL-VERSION      CONTAINER-RUNTIME
kind-control-plane   Ready    control-plane,master   2m37s   v1.20.2   172.18.0.2    <none>        Ubuntu 20.10   4.19.121-linuxkit   containerd://1.4.0-106-gce4439a8

helm install --wait --timeout 60s \ 
          cert-manager jetstack/cert-manager \
          --namespace cert-manager \
          --version v1.2.0 \
          --set 'extraArgs={--dns01-recursive-nameservers=8.8.8.8:53\,1.1.1.1:53}' \
          --create-namespace \
          --set installCRDs=true

helm install --wait --timeout 60s cert-manager-webhook-duckdns \
          --namespace cert-manager \
          --set duckdns.domain='****.duckdns.org' \
          --set duckdns.token='*****' \
          --set clusterIssuer.production.create=false \
          --set clusterIssuer.staging.create=false \
          --set clusterIssuer.email=***** \
          --set logLevel=2 \
          ./charts/cert-manager-webhook-duckdns

cat << EOF | kubectl apply -f -
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-webhook-duckdns-staging
  labels:
    app: cert-manager-webhook-duckdns
spec:
  acme:
    email: ****
    privateKeySecretRef:
      name: cert-manager-webhook-duckdns-staging
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        webhook:
          config:
            domain: *****duckdns.org
            apiTokenSecretRef:
              key: token
              name: cert-manager-webhook-duckdns
          groupName: acme.duckdns.org
          solverName: duckdns
EOF
```
Then I check the ClusterIssuer

```
kc describe clusterissuers.cert-manager.io cert-manager-webhook-duckdns-staging

Name:         cert-manager-webhook-duckdns-staging
Namespace:
Labels:       app=cert-manager-webhook-duckdns
Annotations:  <none>
API Version:  cert-manager.io/v1
Kind:         ClusterIssuer
Metadata:
  Creation Timestamp:  2021-03-24T11:35:14Z
  Generation:          1
  Managed Fields:
    API Version:  cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:app:
      f:spec:
        .:
        f:acme:
          .:
          f:email:
          f:privateKeySecretRef:
            .:
            f:name:
          f:server:
          f:solvers:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2021-03-24T11:35:14Z
    API Version:  cert-manager.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:acme:
          .:
          f:lastRegisteredEmail:
          f:uri:
        f:conditions:
    Manager:         controller
    Operation:       Update
    Time:            2021-03-24T11:35:16Z
  Resource Version:  1117
  UID:               1ffd4c9b-29ba-43bb-8fd5-c50fe9ccf6af
Spec:
  Acme:
    Email:            ******
    Preferred Chain:
    Private Key Secret Ref:
      Name:  cert-manager-webhook-duckdns-staging
    Server:  https://acme-staging-v02.api.letsencrypt.org/directory
    Solvers:
      dns01:
        Webhook:
          Config:
            API Token Secret Ref:
              Key:      token
              Name:     cert-manager-webhook-duckdns
            Domain:     *****.duckdns.org
          Group Name:   acme.duckdns.org
          Solver Name:  duckdns
Status:
  Acme:
    Last Registered Email:  *******
    Uri:                    https://acme-staging-v02.api.letsencrypt.org/acme/acct/18741521
  Conditions:
    Last Transition Time:  2021-03-24T11:35:16Z
    Message:               The ACME account was registered with the ACME server
    Reason:                ACMEAccountRegistered
    Status:                True
    Type:                  Ready
Events:                    <none>
```

**Comment by ElArtista** [comment]
Ah yeah, you must supply `clusterIssuer.{staging|production}.create=true` in order to reproduce this, here is my config:

```
duckdns:
  domain: {{ .Values.duckdns.domain }}
  token: {{ .Values.duckdns.token }}
clusterIssuer:
  email: {{ .Values.duckdns.email }}
  production:
    create: true
  staging:
    create: true
certManager:
  namespace: ingress
logLevel: 6
```

**Comment by ebrianne** [comment]
I have also tried with the value of `true` and I still cannot reproduce the problem. Please provide me with the steps to reproduce it otherwise I'll consider this issue closed.

**Comment by ElArtista** [comment]
I'm cleaning up a demo helmfile + configuration for you to reproduce this, will update soon.

**Comment by ElArtista** [comment]
Minified and fully-reproducible example (just retested latest v1.2 release on a vanilla setup)

Use my repo here: https://github.com/ElArtista/kubelab/tree/56623f1fea1e20860336485dddf3a7def4b69e56
- Bring up a vanilla k8s cluster (you can use my Vagrantfile to simulate a 1 master + 2 workers for this, or anything else)
- Copy `.env.sample.yaml` to `.env.default.yaml` and provide your values accordingly
- Apply cert-manager release using: ```helmfile -f manifests/ingress.yaml -l name=cert-manager apply```
- Wait a while for cert-manager to go up (and register various operations between its modules) and apply the rest releases (for now just cert-manager-webhook-duckdns) using: ```helmfile -f manifests/ingress.yaml apply```

Result as described above:
```
...
Upgrading release=cert-manager-webhook-duckdns, chart=ebrianne.github.io/cert-manager-webhook-duckdns
Release "cert-manager-webhook-duckdns" does not exist. Installing it now.


FAILED RELEASES:
NAME
cert-manager-webhook-duckdns
in manifests/ingress.yaml: failed processing release cert-manager-webhook-duckdns: command "/usr/bin/helm" exited with non-zero status:

PATH:
  /usr/bin/helm

ARGS:
  0: helm (4 bytes)
  1: upgrade (7 bytes)
  2: --install (9 bytes)
  3: --reset-values (14 bytes)
  4: cert-manager-webhook-duckdns (28 bytes)
  5: ebrianne.github.io/cert-manager-webhook-duckdns (47 bytes)
  6: --create-namespace (18 bytes)
  7: --namespace (11 bytes)
  8: ingress (7 bytes)
  9: --values (8 bytes)
  10: /tmp/helmfile444059400/ingress-cert-manager-webhook-duckdns-values-7465cc6fb6 (77 bytes)
  11: --history-max (13 bytes)
  12: 10 (2 bytes)

ERROR:
  exit status 1

EXIT STATUS
  1

STDERR:
  Error: ClusterIssuer.cert-manager.io "cert-manager-webhook-duckdns-production" is invalid: spec.acme.preferredChain: Invalid value: "null": spec.acme.preferredChain in body must be of type string: "null"

COMBINED OUTPUT:
  Release "cert-manager-webhook-duckdns" does not exist. Installing it now.
  Error: ClusterIssuer.cert-manager.io "cert-manager-webhook-duckdns-production" is invalid: spec.acme.preferredChain: Invalid value: "null": spec.acme.preferredChain in body must be of type string: "null"
```

Additional information:
```
> helm version
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16.2"}
```
```
> helmfile version
helmfile version 0.137.0
```

And again, cloning the current repository, and patching ```production.cluster-issuer.yaml``` and ```staging.cluster-issuer.yaml``` templates with ```preferredChain: "ISRG Root X1"``` value as above and applying again fixes it.

**Comment by ebrianne** [comment]
Using your commit: https://github.com/ElArtista/kubelab/commit/56623f1fea1e20860336485dddf3a7def4b69e56

That is really strange I still cannot reproduce the error with your method... It really seems something to be very specific to your environment.
I tried your helm configuration with k3d and kind on MacOS. I tried your vagrant file but it does not work; I needed to patch sth first to avoid the network configuration error and agents cannot join the master throwing bad tls certificate errors. It would take me too much time to setup a proper vagrant file.

For k3d, here is my config:
```yaml
apiVersion: k3d.io/v1alpha2
kind: Simple
name: k3d
servers: 1
agents: 2
image: rancher/k3s:v1.20.4-k3s1
options:
  k3d: 
    wait: true
    timeout: "300s"
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
    disableHostIPInjection: false
  k3s: 
    extraServerArgs:
      - --cluster-cidr=10.68.0.0/16 
      - --service-cidr=10.98.0.0/16 
      - --node-taint=node-role.kubernetes.io/master=true:NoSchedule
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true 
    switchCurrentContext: true
```

For kind, here is my config:
```yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
- role: control-plane
  image: kindest/node:v1.20.2
- role: worker
  image: kindest/node:v1.20.2
- role: worker
  image: kindest/node:v1.20.2
networking:
  podSubnet: "10.68.0.0/16"
  serviceSubnet: "10.98.0.0/16"
```

Concerning your configuration. I just added the chart version for cert-manager-webhook-duckdns to `version: v1.1` and added the email field in the value file as it is needed.

```
Upgrading release=cert-manager-webhook-duckdns, chart=ebrianne.github.io/cert-manager-webhook-duckdns
Release "cert-manager-webhook-duckdns" does not exist. Installing it now.
NAME: cert-manager-webhook-duckdns
LAST DEPLOYED: Fri Mar 26 16:00:52 2021
NAMESPACE: ingress
STATUS: deployed
REVISION: 1
TEST SUITE: None

Listing releases matching ^cert-manager-webhook-duckdns$
cert-manager-webhook-duckdns    ingress         1               2021-03-26 16:00:52.922758 +0100 CET    deployed        cert-manager-webhook-duckdns-v1.1       v1.1       


UPDATED RELEASES:
NAME                           CHART                                             VERSION
cert-manager-webhook-duckdns   ebrianne.github.io/cert-manager-webhook-duckdns      v1.1
```

Also I have the latest helm, helmfile and helm diff plugins
```
version.BuildInfo{Version:"v3.5.3", GitCommit:"041ce5a2c17a58be0fcd5f5e16fb3e7e95fea622", GitTreeState:"dirty", GoVersion:"go1.16"}
```
```
helmfile version v0.138.7
```

Just as a side note, I tired before to use alpine as OS for my personal k3s cluster but I noticed that I ran into a lot of troubles with it.... so maybe change to ubuntu 20.04.

**Comment by ElArtista** [comment]
My Vagrantfile relies on latest vagrant master because it is using alpine313 box. Changing it to alpine312 box should work without the network problems.

I'm still trying to pinpoint the problem, seems that just applying a simple ClusterIssuer yaml you provided in a comment  above:
```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cert-manager-webhook-duckdns-staging-test
  labels:
    app: cert-manager-webhook-duckdns
spec:
  acme:
    email: somemail@example.com
    privateKeySecretRef:
      name: cert-manager-webhook-duckdns-staging-test
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
    - dns01:
        webhook:
          config:
            domain: example.duckdns.org
            apiTokenSecretRef:
              key: token
              name: cert-manager-webhook-duckdns
          groupName: acme.duckdns.org
          solverName: duckdns
```
with
```
kubectl apply -f clusterissuer.yaml
```
Still results in:
```
The ClusterIssuer "cert-manager-webhook-duckdns-staging-test" is invalid: spec.acme.preferredChain: Invalid value: "null": spec.acme.preferredChain in body must be of type string: "null"
```
I'll try running my helmfile in a k3d cluster to confirm.
